export enum Namespaces {
  LOCALE = 'LOCALE',
  ROUTER = 'router',
  USER = 'USER',
  UI = 'UI',
  APPSTATE = 'APPSTATE',
  TODAYS_APPOINTMENTS = 'TODAYS_APPOINTMENTS',
  CURRENT_APPOINTMENT = 'CURRENT_APPOINTMENT',
  OVERVIEW_WIDGETS = 'OVERVIEW_WIDGETS',
  SITE = 'SITE',
  CHECKOUT_APPOINTMENTS = 'CHECKOUT_APPOINTMENTS',
}
