# Resource repository where pipeline templates located.
# This is mandatory for linking to templates in other repository.
resources:
  repositories:
  - repository: duly-terraform-manifest
    type: git
    name: duly-terraform-manifest
    ref: 'refs/heads/dev'

pool: OnAKS


trigger: none


stages:
- template: ./_pipelines/templates/stages/full-iac-deployment-stage.yml@duly-terraform-manifest
  parameters:
    infraSolutionRepo: duly-terraform-manifest
    configurationRepo: duly-terraform-manifest
    
    ### The array of environments for deployment.
    envList:
    # - azure_cloud_np
    - azure_cloud_prod
    # - prod
    ### The array of Terraform solutions which are grouped to be deployed simultaneously. After the first array's item, 'dependsOnIndex' property is required.
    ### 'dependsOnIndex' property detremines Terraform solutions group as an array item number, after which current solutions group shoud be deployed.
    infraSolutionSequence:
      - solutions:
        - 001_rg
      - dependsOnIndex: 0
        solutions:
        - 002_logAnalytics
        - 002_netwatcher
      - dependsOnIndex: 1
        solutions:
        - 003_vnet
        - 003_appInsight
      - dependsOnIndex: 2
        solutions:
        - 004_keyVault
        - 004_publicip
        - 004_udr
        - 004_NSG
      - dependsOnIndex: 3
        solutions:
        - 005_private_dns
        # - 005_appgtw
        - 005_MSSQLserver
      - dependsOnIndex: 4
        solutions:
        - 006_uai
      - dependsOnIndex: 5
        solutions:
        - 007_AKS
        - 007_apim
      - dependsOnIndex: 6
        solutions:
        - 008_app_uai
