# Resource repository where pipeline templates located.
# This is mandatory for linking to templates in other repository.
resources:
  repositories:
  - repository: duly-yaml-templates
    type: git
    name: 'duly.digital.devops/duly-yaml-templates'

  - repository: terraform-scripts
    type: git
    name: 'duly.api.v1.integration/terraform-scripts'

pool: OnAKS


trigger: none


stages:
- template: ./child.terraform/stages/full-iac-deployment-stage.yml@duly-yaml-templates
  parameters:
    infraSolutionRepo: terraform-scripts
    configurationRepo: terraform-scripts
    
    ### The array of environments for deployment.
    envList:
    - qat
    - aut
    - uat
    - prd

    ### The array of Terraform solutions which are grouped to be deployed simultaneously. After the first array's item, 'dependsOnIndex' property is required.
    ### 'dependsOnIndex' property detremines Terraform solutions group as an array item number, after which current solutions group shoud be deployed.
    infraSolutionSequence:
      - solutions:
        - keyVault
      # - dependsOnIndex: 0
      #   solutions:
      #   - db
      # - dependsOnIndex: 1
      #   solutions:
      #   # - 003_vnet
      #   # - 004_keyVault
      #   # - 006_ACR
      # - dependsOnIndex: 2
      #   solutions:
        # - 005_vnetpeering
        # - 007_AKS
      # - dependsOnIndex: 3
      #   solutions:
      #   - 012_nsg
      #   - 012_vnetpeering
      #   - 012_azurefirewall
      #   - 012_appgtw
      #   - 012_virtualgtw
      # - dependsOnIndex: 4
      #   solutions:
      #   - 013_udr
      # - dependsOnIndex: 5
      #   solutions:
      #   - 014_keyvault
      #   - 014_recoveryvault
      # - dependsOnIndex: 6
      #   solutions:
      #   - 015_vm
      #   - 015_bastionhost
