defaultPlacement: end
fieldLayouts:
    40391d4b-48ff-49fa-b8b9-83aef065199e: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: eventCategories
name: 'Event Categories'
siteSettings:
    c36fa7d2-e59a-4c88-9f95-780439e98505: { hasUrls: false, template: null, uriFormat: null }
structure:
    maxLevels: null
    uid: c29454df-218f-439a-845c-6b86fdf2d316
