defaultPlacement: end
fieldLayouts:
    9f6ff03b-f2f3-41f1-867e-e48ac16af7cc: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }, { fieldUid: 0c8e35a2-599f-4697-aec5-785fcbb2928d, instructions: null, label: null, required: false, tip: null, type: craft\fieldlayoutelements\CustomField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: expressCareServices
name: 'Express Care Services'
siteSettings:
    c36fa7d2-e59a-4c88-9f95-780439e98505: { hasUrls: true, template: null, uriFormat: 'express-care-services/{slug}' }
structure:
    maxLevels: null
    uid: 74d83d07-0464-4dce-ab0d-25a1edbd914a
