defaultPlacement: end
fieldLayouts:
    adb6481d-a237-4249-a06a-8a1a9a5501fa: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: medicalInterests
name: 'Medical Interests'
siteSettings:
    c36fa7d2-e59a-4c88-9f95-780439e98505: { hasUrls: false, template: null, uriFormat: null }
structure:
    maxLevels: null
    uid: 07ce597c-c4b9-4849-9b5e-e5b1060af3aa
