defaultPlacement: end
fieldLayouts:
    04f7029e-5a46-4839-bad6-e0278f4eeee5: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }, { fieldUid: 0c8e35a2-599f-4697-aec5-785fcbb2928d, instructions: null, label: null, required: false, tip: null, type: craft\fieldlayoutelements\CustomField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: physicalAndOccupationalTherapyServices
name: 'Physical and Occupational Therapy Services'
siteSettings:
    c36fa7d2-e59a-4c88-9f95-780439e98505: { hasUrls: true, template: null, uriFormat: 'physical-and-occupational-therapy-services/{slug}' }
structure:
    maxLevels: null
    uid: 097a7972-d621-4e99-856a-6c03ea3f9a7b
