defaultPlacement: end
fieldLayouts:
    4fd4763b-9538-4990-b089-f012e6e383b6: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }, { fieldUid: 0c8e35a2-599f-4697-aec5-785fcbb2928d, instructions: '', label: '', required: '1', tip: null, type: craft\fieldlayoutelements\CustomField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: telemedicineServices
name: 'Telemedicine Services'
siteSettings:
    c36fa7d2-e59a-4c88-9f95-780439e98505: { hasUrls: false, template: null, uriFormat: null }
structure:
    maxLevels: null
    uid: 5482f8fc-304a-4ffa-840a-639a82b63655
