import {
  followUpDefault, 
  followUpComplete, 
  followUpCurrent, 
  labsDefault, 
  labsComplete, 
  labsCurrent, 
  imagingDefault, 
  imagingComplete, 
  imagingCurrent, 
  referralsDefault, 
  referralsComplete, 
  referralsCurrent, 
  prescriptionsDefault, 
  prescriptionsComplete, 
  prescriptionsCurrent, 
  inactiveStep, 
  currentStep,
  checkCircleBlue,
  followUpSkip,
  labsSkip,
  imagingSkip,
  referralsSkip,
  prescriptionsSkip,
  partialLabs,
  partialReferral,
  partialImaging
} from '@icons';
import { CheckoutSideNavType } from '@types';

export const AfterVisitSteps = {
  FOLLOW_UP: 'follow-up',
  LAB: 'lab',
  IMAGING: 'imaging',
  REFERRALS: 'referrals',
  PRESCRIPTIONS: 'prescriptions',
  AFTER_VISIT_SUMMARY: 'next-steps-complete',
};

export const SideNavMockData: CheckoutSideNavType = {
  list: [
    {
      id: 1,
      text: 'Follow-Up',
      value: AfterVisitSteps.FOLLOW_UP,
      completed: false,
      defaultIcon: followUpDefault,
      completeIcon: followUpComplete,
      currentIcon: followUpCurrent,
      skipIcon: followUpSkip,
    },
    {
      id: 2,
      text: 'Labs',
      value: AfterVisitSteps.LAB,
      completed: false,
      defaultIcon: labsDefault,
      completeIcon: labsComplete,
      currentIcon: labsCurrent,
      partialIcon: partialLabs,
      skipIcon: labsSkip,
    },
    {
      id: 3,
      text: 'Imaging',
      value: AfterVisitSteps.IMAGING,
      completed: false,
      defaultIcon: imagingDefault,
      completeIcon: imagingComplete,
      currentIcon: imagingCurrent,
      partialIcon: partialImaging,
      skipIcon: imagingSkip,
    },
    {
      id: 4,
      text: 'Referrals',
      value: AfterVisitSteps.REFERRALS,
      completed: false,
      defaultIcon: referralsDefault,
      completeIcon: referralsComplete,
      currentIcon: referralsCurrent,
      partialIcon: partialReferral,
      skipIcon: referralsSkip,
    },
    {
      id: 5,
      text: 'Prescriptions',
      value: AfterVisitSteps.PRESCRIPTIONS,
      completed: false,
      defaultIcon: prescriptionsDefault,
      completeIcon: prescriptionsComplete,
      currentIcon: prescriptionsCurrent,
      skipIcon: prescriptionsSkip,
    },
    {
      id: 6,
      text: 'After Visit Steps Complete',
      value: AfterVisitSteps.AFTER_VISIT_SUMMARY,
      completed: false,
      defaultIcon: inactiveStep,
      completeIcon: checkCircleBlue,
      currentIcon: currentStep,
      skipIcon: currentStep,
    },
  ],
};
