parameters:
  - name: subscriptionName
    type: string
    default: ''
  - name: apimName
    type: string
    default: ''
  - name: apimRgName
    type: string
    default: ''
  - name: saName
    type: string
    default: ''
  - name: saRgName
    type: string
    default: ''
  - name: backupContainerName
    type: string
    default: 'backup-container'

steps:
  - task: AzurePowerShell@5
    displayName: 'Configuration Backup for ${{ parameters.apimName }}'
    inputs:
      azureSubscription: ${{ parameters.subscriptionName }}
      ScriptType: 'FilePath'
      ScriptPath: 'scripts/configuration-backup.ps1'
      ScriptArguments: '-apimRgName ${{ parameters.apimRgName }} -apimName ${{ parameters.apimName }} -saRgName ${{ parameters.saRgName }} -saName ${{ parameters.saName }} -containerName ${{ parameters.backupContainerName }}'
      azurePowerShellVersion: 'LatestVersion'
      workingDirectory: '$(Build.SourcesDirectory)'
