CREATE USER [EPAM-DEV-GRP] FOR EXTERNAL PROVIDER;
GO

GRANT CONNECT TO [EPAM-DEV-GRP];
GO

ALTER ROLE [db_datawriter] ADD MEMBER [EPAM-DEV-GRP];
GO

ALTER ROLE [db_datareader] ADD MEMBER [EPAM-DEV-GRP];
GO