export enum StepperTitles {
  FOLLOW_UP = 'FOLLOW_UP',
  LABS = 'LABS',
  IMAGING = 'IMAGING',
  REFERRAL = 'REFERRAL',
  PRESCRIPTION = 'PRESCRIPTION',
  LAB_LOCATIONS = 'LAB_LOCATIONS',
  IMAGING_LOCATION = 'IMAGING_LOCATION',
  PREFERRED_PHARMACY = 'PREFERRED_PHARMACY',
}
