handle: primaryNavigation
instructions: 'The primary navigation for the site defines what links should appear in the top bar, and what child elements they should have. Use the pipe "|" character to separate the primary title from any descriptive content you wish to appear under a sub-resource.'
name: 'Primary Navigation'
propagateNodes: true
sortOrder: null
structure:
    maxLevels: '1'
    uid: 05222df8-c164-45e6-8154-7ca985a78898
