handle: secondaryNavigation
instructions: 'The secondary navigation is a link-only navigation menu that appears at the very top of the site.'
name: 'Secondary Navigation'
propagateNodes: true
sortOrder: 1
structure:
    maxLevels: null
    uid: 7f1cd7ed-bdaf-413d-951e-a4afc5d5e4d0
