apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AZP_POOL: {{ .Values.azp_pool | b64enc | quote }}
  AZP_TOKEN: {{ .Values.azp_token | b64enc | quote }}
  AZP_URL: {{ .Values.azp_url | b64enc | quote }}
