import {
  DrAbhaProfileImage,
  DrMaryProfileImage,
  locIcon,
  purpalLocationIcon,
  DrSapanProfileImage,
  blueLocationIcon,
  crossIcon,
  DrMorrisProfileImage,
  DrSussmanProfileImage,
  DrPalmeroProfileImage
} from '@icons';

export const ChooseProviderData = {
  location: '233 S Craig PI,',
  pincode: 'Lombard, IL 60148',
  doctors: {
    Gastroenterology: [
      {
        imageIcon: DrSapanProfileImage,
        drName: 'Dr. Grant D. Sievertsen',
        drSpecialization: 'Endocrinologist',
        drLocation: 'Lombard',
        locationInfo: '(2.74 miles from you)',
        location: '2340 S. Highland Ave,',
        pincode: 'Lombard, IL 60148',
      },
      {
        imageIcon: DrMaryProfileImage,
        drName: 'Dr. Hafsa Amjed',
        drSpecialization: 'Endocrinologist',
        drLocation: 'Lombard',
        locationInfo: '(2.79 miles from you)',
        location: '1801 S. Highland Ave,',
        pincode: 'Lombard, IL 60148',
      },
      {
        imageIcon: DrAbhaProfileImage,
        drName: 'Dr. Winnie Nhan',
        drSpecialization: 'Endocrinologist',
        drLocation: 'Lombard',
        locationInfo: '(2.79 miles from you)',
        location: '1801 S. Highland Ave,',
        pincode: 'Lombard, IL 60148',
      },
      {
        imageIcon: DrMorrisProfileImage,
        drName: 'Dr. Rameez Alsadi',
        drSpecialization: 'Endocrinologist',
        drLocation: 'Channahon',
        locationInfo: '(25.1 miles from location)',
        location: '100 Spalding DR',
        pincode: 'Channahon, IL 60410',
      },
      {
        imageIcon: DrPalmeroProfileImage,
        drName: 'Dr. Danish Shahab',
        drSpecialization: 'Endocrinologist',
        drLocation: 'Channahon',
        locationInfo: '(27.7 miles from location)',
        location: '4575 Weaver Parkway',
        pincode: 'Channahon, IL 60410',
      },
      {
        imageIcon: DrSussmanProfileImage,
        drName: 'Dr. Gloria Caruso',
        drSpecialization: 'Endocrinologist',
        drLocation: 'Channahon',
        locationInfo: '(37.9 miles from location)',
        location: '220 SpringField DR',
        pincode: 'Channahon, IL 60410',
      },
    ],
    Dermatologist: [
      {
        imageIcon: DrAbhaProfileImage,
        drName: 'Dr. Nancy C. Lichon',
        drSpecialization: 'Dermatologist',
        drLocation: 'Lombard',
        locationInfo: '(2.74 miles from you)',
        location: '2340 S. Highland Ave,',
        pincode: 'Lombard, IL 60148',
      },
      {
        imageIcon: DrSapanProfileImage,
        drName: 'Dr. Molly Gerber',
        drSpecialization: 'Dermatologist',
        drLocation: 'Lombard',
        locationInfo: '(2.79 miles from you)',
        location: '1801 S. Highland Ave,',
        pincode: 'Lombard, IL 60148',
      },
      {
        imageIcon: DrMaryProfileImage,
        drName: 'Dr. Andrea Rutherford',
        drSpecialization: 'Dermatologist',
        drLocation: 'Lombard',
        locationInfo: '(2.79 miles from you)',
        location: '1801 S. Highland Ave,',
        pincode: 'Lombard, IL 60148',
      },
      {
        imageIcon: DrPalmeroProfileImage,
        drName: 'Dr. James Herrmann',
        drSpecialization: 'Dermatologist',
        drLocation: 'Wheaton',
        locationInfo: '(8.83 miles from location)',
        location: '199 Town Square,',
        pincode: 'Wheaton, IL 60189',
      },
      {
        imageIcon: DrSussmanProfileImage,
        drName: 'Dr. Sarah Kovarik',
        drSpecialization: 'Dermatologist',
        drLocation: 'Wheaton',
        locationInfo: '(8.83 miles from location)',
        location: '199 Town Square,',
        pincode: 'Wheaton, IL 60189',
      },
      {
        imageIcon: DrMorrisProfileImage,
        drName: 'Dr. Elana Dubin',
        drSpecialization: 'Dermatologist',
        drLocation: 'Wheaton',
        locationInfo: '(8.83 miles from location)',
        location: '199 Town Square,',
        pincode: 'Wheaton, IL 60189',
      },
    ],
  },
  locationIcon: locIcon,
  purpalLocationIcon: purpalLocationIcon,
  blueLocationIcon: blueLocationIcon,
  headerCloseBtn: crossIcon,
};
