import { CommunicationType } from '@enums';
import { CommunicationMessage } from '@types';

import { pickPDById } from './personal-data';

export const communicationMockData: CommunicationMessage[] = [
  {
    messageId: 1001,
    incoming: true,
    counterpart: pickPDById(101),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.CALL,
    recipient: [ 'You' ],
    content: 'Call Notes: Hey Ana, I checked in with Euan about meds because...',
    viewed: true,
  },
  {
    messageId: 1002,
    incoming: false,
    counterpart: pickPDById(202),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.CHAT,
    recipient: [ 'Clinical Team' ],
    content: 'Hey Team! Quick scheduling question about our appts...',
    viewed: false,
    replyTo: 1005,
  },
  {
    messageId: 1003,
    incoming: false,
    counterpart: pickPDById(102),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.TEXT,
    recipient: [ 'You' ],
    content: 'Wondering about the stuff you mentioned when we...',
    viewed: true,
  },
  {
    messageId: 1004,
    incoming: true,
    counterpart: pickPDById(103),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.EMAIL,
    recipient: [ 'Care Ally', 'Aiyla Payne' ],
    content: 'Hey Helen, I checked in with Euan about meds because...',
    viewed: false,
  },
  {
    messageId: 1005,
    incoming: false,
    counterpart: pickPDById(201),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.CHAT,
    recipient: [ 'Clinical Team' ],
    content: 'Hey Team! Quick scheduling question about our appts...',
    viewed: true,
  },
  {
    messageId: 1006,
    incoming: false,
    counterpart: pickPDById(104),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.TEXT,
    recipient: [ 'You' ],
    content: 'Wondering about the stuff you mentioned when we...',
    viewed: true,
  },
  {
    messageId: 1007,
    incoming: true,
    counterpart: pickPDById(105),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.EMAIL,
    recipient: [ 'Care Ally', 'Aiyla Payne' ],
    content: 'Hey Helen, I checked in with Euan about meds because...',
    viewed: false,
    replyTo: 1006,
  },
  {
    messageId: 1008,
    incoming: false,
    counterpart: pickPDById(202),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.CHAT,
    recipient: [ 'Clinical Team' ],
    content: 'Hey Team! Quick scheduling question about our appts...',
    viewed: true,
  },
  {
    messageId: 1009,
    incoming: false,
    counterpart: pickPDById(101),
    time: '0/0/00 0:00 AM',
    via: CommunicationType.TEXT,
    recipient: [ 'You' ],
    content: 'Wondering about the stuff you mentioned when we...',
    viewed: true,
  },
];
