import {
  DrAbhaProfileImage,
  DrMaryProfileImage,
  DrSapanProfileImage,
  DrMorrisProfileImage,
  DrSussmanProfileImage,
  DrPalmeroProfileImage
} from '@icons';

export const ProvidersDetailsList = [
  {
    id:1,
    providerId: 'sc2provider1',
    providerName: 'John, Reilly',
    providerDisplayName: 'Reilly',
    locationLatitudeCoordinate: '28.526750',
    locationLongitudeCoordinate: '77.381745',
    city: 'Elmhurst',
    providerSpecialty: 'GASTROENTEROLOGY',
    distance: 1330.3211197265914,
    providerPhotoURL: DrMorrisProfileImage,
    locationId: '12313',
    locationName: '133 E. Brush Hill Road',
    locationAdd_1: '133 E. Brush Hill Road',
    locationState: 'Illionis',
    locationZip: '60189',
  },
  {
    id: 2,
    providerId:'sc2provider2',
    providerName: 'Grant, D., Sievertsen',
    providerDisplayName: 'Sievertsen',
    locationLatitudeCoordinate: '28.523130',
    locationLongitudeCoordinate: '77.394457',
    city: 'Lombard',
    providerSpecialty: 'GASTROENTEROLOGY',
    distance: 1413.2335674635078,
    providerPhotoURL: DrMaryProfileImage,
    locationId: '12312',
    locationName: '2340 S Highland Ave',
    locationAdd_1: '2340 S Highland Ave',
    locationState: 'Illionis',
    locationZip: '60148',
  },
  {
    id: 3,
    providerId:'sc2provider3',
    providerName: 'Hafsa, Amjed',
    providerDisplayName: 'Amjed',
    locationLatitudeCoordinate: '28.528560',
    locationLongitudeCoordinate: '77.403389',
    city: 'Lombard',
    providerSpecialty: 'GASTROENTEROLOGY',
    distance: 1434.5499055563496,
    providerPhotoURL: DrSapanProfileImage,
    locationId: '12312',
    locationName: '1801 S Highland Ave',
    locationAdd_1: '1801 S Highland Ave',
    locationState: 'Illionis',
    locationZip: '60148',
  }, 
  {
    id: 5,
    providerId:'sc2provider5',
    providerName: 'Rameez, Alsadi',
    providerDisplayName: 'Alsadi',
    locationLatitudeCoordinate: '28.528560',
    locationLongitudeCoordinate: '77.403389',
    city: 'Lombard',
    providerSpecialty: 'PHYSICAL THERAPY',
    distance: 1434.5499055563496,
    providerPhotoURL: DrSussmanProfileImage,
    locationId: '12312',
    locationName: '2340 S Highland Ave',
    locationAdd_1: '2340 S Highland Ave',
    locationState: 'Illionis',
    locationZip: '60148',
  },  
  {
    id: 6,
    providerId:'sc2provider6',
    providerName: 'Molly, Gerber',
    providerDisplayName: 'Gerber',
    locationLatitudeCoordinate: '28.528560',
    locationLongitudeCoordinate: '77.403389',
    city: 'Lombard',
    providerSpecialty: 'PHYSICAL THERAPY',
    distance: 1434.5499055563496,
    providerPhotoURL: DrAbhaProfileImage,
    locationId: '12312',
    locationName: '1801 S Highland Ave',
    locationAdd_1: '1801 S Highland Ave',
    locationState: 'Illionis',
    locationZip: '60148',
  },  
  {
    id: 7,
    providerId:'sc2provider7',
    providerName: 'Andrea, Rutherford',
    providerDisplayName: 'RutherFord',
    locationLatitudeCoordinate: '28.528560',
    locationLongitudeCoordinate: '77.403389',
    city: 'Lombard',
    providerSpecialty: 'PHYSICAL THERAPY',
    distance: 1434.5499055563496,
    providerPhotoURL: DrPalmeroProfileImage,
    locationId: '12312',
    locationName: '1801 S Highland Ave',
    locationAdd_1: '1801 S Highland Ave',
    locationState: 'Illionis',
    locationZip: '60148',
  },
];

export const ReferralsDetails = [ 
  { providerType: 'Gastroenterology' }, 
  { providerType: 'Physical Therapy' }, 
  { providerType: 'Dermatology' },
];
