fieldLayouts:
    3fc67ea3-fc41-48b3-a2b3-fe2ee076ff22: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: procedureImages
hasUrls: true
name: 'Procedure Images'
settings:
    accountKey: $AZURE_STORAGE_ACCOUNT_KEY
    accountName: $AZURE_STORAGE_ACCOUNT_NAME
    azureStorageType: blob
    blobEndpoint: ''
    containerName: $AZURE_STORAGE_CONTAINER_NAME
    subfolder: procedure-images
sortOrder: 9
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: shennyg\azureblobremotevolume\AzureVolume
url: '@assetBaseUrl'
