fieldLayouts:
    6983fcb6-e560-41b4-b41e-8a8926691f22: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: scheduleServiceTileIcons
hasUrls: true
name: 'Schedule Service Tile Icons'
settings:
    accountKey: $AZURE_STORAGE_ACCOUNT_KEY
    accountName: $AZURE_STORAGE_ACCOUNT_NAME
    azureStorageType: blob
    blobEndpoint: ''
    containerName: $AZURE_STORAGE_CONTAINER_NAME
    subfolder: service-tile-icons
sortOrder: 11
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: shennyg\azureblobremotevolume\AzureVolume
url: '@assetBaseUrl'
