fieldLayouts:
    c4ff0ebc-7fad-4c8b-8bfc-d09e2fe4eef8: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: null, max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\TitleField, warning: null, width: 100 }], name: Content, sortOrder: 1 }] }
handle: treatmentStyleImages
hasUrls: true
name: 'Treatment Style Images'
settings:
    accountKey: $AZURE_STORAGE_ACCOUNT_KEY
    accountName: $AZURE_STORAGE_ACCOUNT_NAME
    azureStorageType: blob
    blobEndpoint: ''
    containerName: $AZURE_STORAGE_CONTAINER_NAME
    subfolder: treatment-style-images
sortOrder: 13
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: shennyg\azureblobremotevolume\AzureVolume
url: '@assetBaseUrl'
