# Template for pushing Docker image to Azure Container Registry

parameters:
- name: containerRegistry
  type: string
- name: repository
  type: string
- name: dockerFile
  type: string
- name: tags
  type: string

steps:
- task: Docker@2
  displayName: Push image to Azure Container Registry
  inputs:
    command: push
    containerRegistry: ${{ parameters.containerRegistry }}
    repository: ${{ parameters.repository }}
    Dockerfile: ${{ parameters.dockerFile }}
    tags: ${{ parameters.tags }}