defaultPlacement: end
enableVersioning: true
handle: services
name: Services
previewTargets:
    - { __assoc__: [[label, 'Primary entry page'], [urlFormat, '{url}'], [refresh, '']] }
propagationMethod: all
siteSettings:
    c36fa7d2-e59a-4c88-9f95-780439e98505: { enabledByDefault: true, hasUrls: true, template: _services/_single-service, uriFormat: 'services/{slug}' }
structure:
    maxLevels: null
    uid: 158a3db1-9dba-49b0-a6cb-7414cdec9202
type: structure
