defaultPlacement: end
enableVersioning: true
handle: thankYouPage
name: 'Thank You Page'
previewTargets:
    - { __assoc__: [[label, 'Primary entry page'], [urlFormat, '{url}'], [refresh, '1']] }
propagationMethod: all
siteSettings:
    c36fa7d2-e59a-4c88-9f95-780439e98505: { enabledByDefault: true, hasUrls: true, template: null, uriFormat: thank-you-page }
type: single
