columnSuffix: null
contentColumnType: string
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: ageRestrictions
instructions: 'Select if this physician only see patients of a certain age group.'
name: 'Age Restrictions'
searchable: true
settings:
    contentTable: '{{%matrixcontent_agerestrictions}}'
    maxBlocks: '1'
    minBlocks: '1'
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
