columnSuffix: null
contentColumnType: boolean
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: allowsOnlineScheduling
instructions: ''
name: 'Allows Online Scheduling'
searchable: true
settings:
    default: true
    offLabel: null
    onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
