columnSuffix: null
contentColumnType: boolean
fieldGroup: 970af1ca-372b-4267-b767-7366ce069711
handle: allowOnlineScheduling
instructions: 'Indicates if patients can schedule appointments online for this service.'
name: 'Allow Online Scheduling'
searchable: false
settings:
    default: false
    offLabel: null
    onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
