columnSuffix: null
contentColumnType: text
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: alternativeSearchName
instructions: "If this physician is more well-known by a specific name rather than their legal name, provide that name here. \r\nThis can include maiden names as well as shortened names (Nick vs Nicholas)."
name: 'Alternative Search Name'
searchable: true
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: null
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
