columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 188a7201-acbb-4843-a517-affbd2d8231f
handle: annualPhysicalVisitTypeCodeMedicarePlans
instructions: 'This is the visit type code used for "Annual Physical (New and Established Patients)" scheduled appointments for Medicare plans only.'
name: '"Annual Physical (New and Established Patients)" Visit Type Code (Medicare plans only)'
searchable: true
settings:
    decimals: 0
    defaultValue: null
    max: null
    min: 0
    prefix: null
    previewCurrency: ''
    previewFormat: none
    size: null
    suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
