columnSuffix: null
contentColumnType: text
fieldGroup: 0005db84-4545-45f0-9f3f-f2ba868a0ae6
handle: brand
instructions: ''
name: Brand
searchable: false
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: null
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
