columnSuffix: null
contentColumnType: string
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: careerStartDate
instructions: 'When did this physician start their career?'
name: 'Career Start Date'
searchable: true
settings:
    contentTable: '{{%matrixcontent_careerstartdate}}'
    maxBlocks: '1'
    minBlocks: ''
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
