columnSuffix: null
contentColumnType: text
fieldGroup: 988e27dc-4f40-4d11-b083-12b7ab05b5d4
handle: conditionDescription
instructions: 'Select any conditions related to this service.'
name: 'Condition Description'
searchable: true
settings:
    availableTransforms: '*'
    availableVolumes: [2f2dfc80-9a9c-4222-beec-c87940405035]
    columnType: text
    configSelectionMode: choose
    defaultTransform: ''
    manualConfig: ''
    purifierConfig: ''
    purifyHtml: ''
    redactorConfig: Standard.json
    removeEmptyTags: '1'
    removeInlineStyles: '1'
    removeNbsp: '1'
    showHtmlButtonForNonAdmins: true
    showUnpermittedFiles: false
    showUnpermittedVolumes: false
    uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
