columnSuffix: null
contentColumnType: string
fieldGroup: 988e27dc-4f40-4d11-b083-12b7ab05b5d4
handle: conditionHeroImage
instructions: 'Upload an image related to this condition.'
name: 'Condition Hero Image'
searchable: true
settings:
    allowSelfRelations: false
    allowUploads: true
    allowedKinds: null
    defaultUploadLocationSource: 'volume:2b01430a-33e9-44a6-87d1-5381ad9be60d'
    defaultUploadLocationSubpath: ''
    limit: ''
    localizeRelations: false
    previewMode: full
    restrictFiles: ''
    selectionLabel: ''
    showSiteMenu: true
    showUnpermittedFiles: false
    showUnpermittedVolumes: true
    singleUploadLocationSource: 'volume:2f2dfc80-9a9c-4222-beec-c87940405035'
    singleUploadLocationSubpath: ''
    source: null
    sources: '*'
    targetSiteId: null
    useSingleFolder: true
    validateRelatedElements: false
    viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
