columnSuffix: null
contentColumnType: text
fieldGroup: 970af1ca-372b-4267-b767-7366ce069711
handle: customSeoMetaTitle
instructions: 'Enter a custom meta description for SEO purposes on this entry. If left blank, the default title will be displayed.'
name: 'Custom SEO Meta Title '
searchable: false
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: null
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
