columnSuffix: xcpltkvg
contentColumnType: text
fieldGroup: 2100fbc6-d68d-4185-8504-3ff4680dee28
handle: customSeoMetaTitlePhysiciansListPage
instructions: 'Enter a custom meta description for SEO purposes on the Physicians List Page. If left blank, the default title will be displayed.'
name: 'Custom SEO Meta Title - Physicians List Page'
searchable: false
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: null
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
