columnSuffix: null
contentColumnType: mediumtext
fieldGroup: 49194be8-0adc-41cb-894d-e3e98a5441c0
handle: eventDescription
instructions: 'Details of the event.'
name: Description
searchable: true
settings:
    availableTransforms: '*'
    availableVolumes: [af867b2c-ed72-4fe4-b18a-148c2ffb780d]
    columnType: mediumtext
    configSelectionMode: choose
    defaultTransform: ''
    manualConfig: ''
    purifierConfig: ''
    purifyHtml: ''
    redactorConfig: Standard.json
    removeEmptyTags: '1'
    removeInlineStyles: '1'
    removeNbsp: '1'
    showHtmlButtonForNonAdmins: true
    showUnpermittedFiles: false
    showUnpermittedVolumes: false
    uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
