columnSuffix: null
contentColumnType: string
fieldGroup: a3f678ff-f37b-45e3-9eb0-08e2d122029b
handle: featuredService
instructions: 'Select two services to be featured on the scheduling landing page.'
name: 'Featured Service'
searchable: true
settings:
    contentTable: '{{%matrixcontent_featuredservice}}'
    maxBlocks: '2'
    minBlocks: '2'
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
