columnSuffix: null
contentColumnType: text
fieldGroup: c36a717d-daaf-4fa8-82e7-c1e4dbd8ba3b
handle: heroSectionHeroSubTitle
instructions: ''
name: 'Hero Section Title'
searchable: true
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: text
    initialRows: '4'
    multiline: ''
    placeholder: 'Not everyone operates on business hours.'
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
