columnSuffix: null
contentColumnType: text
fieldGroup: c36a717d-daaf-4fa8-82e7-c1e4dbd8ba3b
handle: immediateCareCheckSymptomsDescription
instructions: ''
name: 'Check Symptoms - Description'
searchable: true
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: 'Tell us about your symptoms and we will tell you where to find the right care for you.'
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
