columnSuffix: null
contentColumnType: text
fieldGroup: c36a717d-daaf-4fa8-82e7-c1e4dbd8ba3b
handle: immediateCareCheckSymptomsCheckboxCopy
instructions: ''
name: 'Check Symptoms - Checkbox Copy'
searchable: true
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: 'I am checking on behalf of someone else'
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
