columnSuffix: null
contentColumnType: text
fieldGroup: c36a717d-daaf-4fa8-82e7-c1e4dbd8ba3b
handle: immediateCareCheckSymptomsTitle
instructions: ''
name: 'Check Symptoms - Title'
searchable: true
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: 'Let us help you find the right care.'
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
