columnSuffix: null
contentColumnType: string
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: internships
instructions: 'Provide any internships that this physician completed. '
name: Internships
searchable: true
settings:
    contentTable: '{{%matrixcontent_internships}}'
    maxBlocks: ''
    minBlocks: ''
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
