columnSuffix: null
contentColumnType: boolean
fieldGroup: 5aee8925-b56d-4fb5-b087-351dd8200f10
handle: isPlanMedicare
instructions: 'Whether or not the plan is a medicare plan.'
name: 'Is Medicare?'
searchable: false
settings:
    default: false
    offLabel: null
    onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
