columnSuffix: null
contentColumnType: string
fieldGroup: ac484169-52dc-4733-8512-87651a3265d5
handle: landingPageResources
instructions: ''
name: 'Landing Page Resources'
searchable: false
settings:
    contentTable: '{{%matrixcontent_landingpageresources}}'
    maxBlocks: ''
    minBlocks: '0'
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
