columnSuffix: null
contentColumnType: text
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: lastName
instructions: "Provide the physician's last name.\r\nThis is only used for sorting purposes and is not being displayed anywhere on the client side."
name: 'Last Name'
searchable: false
settings:
    byteLimit: null
    charLimit: null
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: Smith
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
