columnSuffix: null
contentColumnType: string
fieldGroup: 188a7201-acbb-4843-a517-affbd2d8231f
handle: newPatientServiceSpecificVisitTypeCodes
instructions: "You can override the default \"New Patients\" visit type code by adding service-specific code blocks in this section.\r\n\r\nServices selected in this section will NOT be assigned the default \"New Patients\" visit type code, and instead will use the code specified in their respective blocks."
name: '"New Patient" Service-Specific Visit Type Codes'
searchable: false
settings:
    contentTable: '{{%matrixcontent_newpatientservicespecificvisittypecodes}}'
    maxBlocks: ''
    minBlocks: ''
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
