columnSuffix: null
contentColumnType: string
fieldGroup: c36a717d-daaf-4fa8-82e7-c1e4dbd8ba3b
handle: onSiteTesting
instructions: 'Add individual on-site tests that can be done at various facilities.'
name: 'On-Site Testing'
searchable: true
settings:
    contentTable: '{{%matrixcontent_onsitetesting}}'
    maxBlocks: ''
    minBlocks: ''
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
