columnSuffix: null
contentColumnType: string
fieldGroup: 99b92802-afee-4578-b959-de37dfc60066
handle: participatingLocations
instructions: "Select the suites participating in this special.\r\nOnly suites should be selected (and not physical locations)."
name: 'Participating Locations'
searchable: false
settings:
    allowSelfRelations: false
    limit: ''
    localizeRelations: false
    selectionLabel: ''
    showSiteMenu: true
    source: null
    sources: ['section:17cba234-5703-403b-a9e3-d029df2d1745']
    targetSiteId: null
    validateRelatedElements: false
    viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
