columnSuffix: null
contentColumnType: string
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: physicianHospitalAffiliations
instructions: ''
name: 'Hospital Affiliations'
searchable: false
settings:
    allowSelfRelations: false
    limit: ''
    localizeRelations: false
    selectionLabel: ''
    showSiteMenu: true
    source: null
    sources: ['section:2f2fa994-f57a-47d5-ac1b-2211de4e3294']
    targetSiteId: null
    validateRelatedElements: true
    viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
