columnSuffix: null
contentColumnType: text
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: physicianDisclaimerText
instructions: 'Provider an optional disclaimer (250 character max) that will appear in the details for a physician.'
name: 'Physician Disclaimer Text'
searchable: false
settings:
    availableTransforms: '*'
    availableVolumes: ''
    columnType: text
    configSelectionMode: choose
    defaultTransform: ''
    manualConfig: ''
    purifierConfig: ''
    purifyHtml: '1'
    redactorConfig: BoldItalicsUnderlineOnly.json
    removeEmptyTags: '1'
    removeInlineStyles: '1'
    removeNbsp: '1'
    showHtmlButtonForNonAdmins: '1'
    showUnpermittedFiles: true
    showUnpermittedVolumes: true
    uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
