columnSuffix: null
contentColumnType: string
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: physicianCellPhone
instructions: 'Provide a cell phone number to reach this physician.'
name: 'Cell Phone'
searchable: true
settings:
    defaultRegion: US
translationKeyFormat: null
translationMethod: none
type: rynpsc\phonenumber\fields\PhoneNumberField
