columnSuffix: null
contentColumnType: string
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: physicianCertifications
instructions: ''
name: 'Board Certifications'
searchable: false
settings:
    allowLimit: false
    allowMultipleSources: false
    allowSelfRelations: false
    branchLimit: ''
    limit: null
    localizeRelations: false
    selectionLabel: ''
    showSiteMenu: true
    source: 'group:79165dc3-5c73-4a06-a37f-1e76919a4c4b'
    sources: '*'
    targetSiteId: null
    validateRelatedElements: true
    viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
