columnSuffix: null
contentColumnType: string
fieldGroup: cc769682-917d-404b-9f89-de109350bed8
handle: physicianServices
instructions: 'Select a service to show physicians from'
name: Services
searchable: false
settings:
    allowSelfRelations: false
    limit: ''
    localizeRelations: false
    selectionLabel: 'Select a service'
    showSiteMenu: true
    source: null
    sources: ['section:e3299412-d9c2-4679-9fad-64e72b3c5a42']
    targetSiteId: null
    validateRelatedElements: true
    viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
