columnSuffix: null
contentColumnType: string
fieldGroup: 0ed291b1-bfe4-464d-bb86-2bb3b880be78
handle: physicianVideoLinks
instructions: 'Upload YouTube Video links here. First video uploaded will be listed as the primary video of the section.'
name: 'Physician Video Links'
searchable: true
settings:
    contentTable: '{{%matrixcontent_physicianvideolinks}}'
    maxBlocks: ''
    minBlocks: ''
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
