columnSuffix: null
contentColumnType: text
fieldGroup: 750de691-3a32-4215-94f4-39158c2c6646
handle: productsIntroductionText
instructions: 'Enter text to appear above the product listings.'
name: 'Introduction Text'
searchable: false
settings:
    availableTransforms: '*'
    availableVolumes: ''
    columnType: text
    configSelectionMode: choose
    defaultTransform: ''
    manualConfig: ''
    purifierConfig: ''
    purifyHtml: '1'
    redactorConfig: BoldItalicsUnderlineOnly.json
    removeEmptyTags: '1'
    removeInlineStyles: '1'
    removeNbsp: '1'
    showHtmlButtonForNonAdmins: ''
    showUnpermittedFiles: false
    showUnpermittedVolumes: false
    uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
