columnSuffix: null
contentColumnType: text
fieldGroup: 0005db84-4545-45f0-9f3f-f2ba868a0ae6
handle: productDescription
instructions: ''
name: Description
searchable: true
settings:
    availableTransforms: '*'
    availableVolumes: '*'
    columnType: text
    configSelectionMode: choose
    defaultTransform: ''
    manualConfig: ''
    purifierConfig: ''
    purifyHtml: '1'
    redactorConfig: Standard.json
    removeEmptyTags: '1'
    removeInlineStyles: '1'
    removeNbsp: '1'
    showHtmlButtonForNonAdmins: '1'
    showUnpermittedFiles: false
    showUnpermittedVolumes: false
    uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
