columnSuffix: null
contentColumnType: string
fieldGroup: 0005db84-4545-45f0-9f3f-f2ba868a0ae6
handle: productLocations
instructions: 'Only suites should be selected (and not physical locations).'
name: Locations
searchable: false
settings:
    allowSelfRelations: false
    limit: ''
    localizeRelations: false
    selectionLabel: ''
    showSiteMenu: true
    source: null
    sources: ['section:17cba234-5703-403b-a9e3-d029df2d1745']
    targetSiteId: null
    validateRelatedElements: false
    viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
