columnSuffix: null
contentColumnType: boolean
fieldGroup: 970af1ca-372b-4267-b767-7366ce069711
handle: recommendedProvidersNewPatients
instructions: 'Show recommended providers for new patients. '
name: 'Recommended Providers (new patients)'
searchable: false
settings:
    default: false
    offLabel: null
    onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
