columnSuffix: null
contentColumnType: boolean
fieldGroup: 970af1ca-372b-4267-b767-7366ce069711
handle: recommendedProvidersEstablishedPatients
instructions: 'Show recommended providers for established patients.'
name: 'Recommended Providers (established patients)'
searchable: false
settings:
    default: false
    offLabel: null
    onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
