columnSuffix: null
contentColumnType: string
fieldGroup: 970af1ca-372b-4267-b767-7366ce069711
handle: serviceRelatedServices
instructions: 'Select any other services that would be related to this service.'
name: 'Related Services'
searchable: true
settings:
    allowSelfRelations: false
    limit: ''
    localizeRelations: false
    selectionLabel: 'Add a service'
    showSiteMenu: true
    source: null
    sources: ['section:e3299412-d9c2-4679-9fad-64e72b3c5a42']
    targetSiteId: null
    validateRelatedElements: false
    viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
