columnSuffix: null
contentColumnType: string
fieldGroup: bb45064c-bdd5-4ee4-9e20-4f4265207b6c
handle: singlePhysician
instructions: ''
name: 'Single Physician'
searchable: false
settings:
    allowSelfRelations: false
    limit: '1'
    localizeRelations: false
    selectionLabel: ''
    showSiteMenu: false
    source: null
    sources: ['section:a578774f-f4e1-4f95-a2f8-f9b8bae72c8c']
    targetSiteId: null
    validateRelatedElements: false
    viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
