columnSuffix: null
contentColumnType: string(2000)
fieldGroup: dde69d67-b94d-4a76-802d-86ebce30db4b
handle: testimonialBody
instructions: ''
name: Copy
searchable: false
settings:
    byteLimit: null
    charLimit: 500
    code: ''
    columnType: null
    initialRows: '4'
    multiline: ''
    placeholder: null
    uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
