columnSuffix: null
contentColumnType: text
fieldGroup: 84effa33-535f-4fb6-9548-b1093dc01858
handle: treatmentDescription
instructions: 'Describe treatment style and benefits.'
name: 'Treatment Description'
searchable: false
settings:
    availableTransforms: '*'
    availableVolumes: [3c219dc4-6cb7-4662-8598-3e9a9cb80037]
    columnType: text
    configSelectionMode: choose
    defaultTransform: ''
    manualConfig: ''
    purifierConfig: ''
    purifyHtml: '1'
    redactorConfig: Standard.json
    removeEmptyTags: '1'
    removeInlineStyles: '1'
    removeNbsp: '1'
    showHtmlButtonForNonAdmins: '1'
    showUnpermittedFiles: false
    showUnpermittedVolumes: false
    uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
