columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 188a7201-acbb-4843-a517-affbd2d8231f
handle: veinClinicCode
instructions: 'This is the code for when a patient answers yes to the "Is this for a Vein Clinic appointment?" when scheduling through Vascular Surgery only.'
name: 'Vascular Surgery - Vein Clinic Visit Type Code'
searchable: false
settings:
    decimals: 0
    defaultValue: null
    max: null
    min: 0
    prefix: null
    previewCurrency: ''
    previewFormat: none
    size: null
    suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
