columnSuffix: null
contentColumnType: string
fieldGroup: a3f678ff-f37b-45e3-9eb0-08e2d122029b
handle: videoVisitServiceTiles
instructions: ''
name: 'Video Visit Service Tiles'
searchable: true
settings:
    contentTable: '{{%matrixcontent_videovisitservicetiles}}'
    maxBlocks: '10'
    minBlocks: ''
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
