columnSuffix: null
contentColumnType: string
fieldGroup: c36a717d-daaf-4fa8-82e7-c1e4dbd8ba3b
handle: virtualCareSectionCta
instructions: 'If there is a Virtual Care section, provide CTAs that will be displayed inside this section'
name: 'Virtual Care Section CTA'
searchable: true
settings:
    contentTable: '{{%matrixcontent_virtualcaresectioncta}}'
    maxBlocks: ''
    minBlocks: ''
    propagationKeyFormat: null
    propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
