import { MINUTES_PER_HOUR } from './date-time-constants';

export const HEIGHT_HOUR_SEGMENT = 15.625;
export const HEIGHT_ONE_MINUTE_SEGMENT = HEIGHT_HOUR_SEGMENT / MINUTES_PER_HOUR;
export const HEIGHT_QUARTER_SEGMENT = HEIGHT_HOUR_SEGMENT / 4;
export const PADDING_TOP_SCHEDULER_SCALE = 0.25;
export const PADDING_BOTTOM_SCHEDULER_SCALE = 0.5;
export const HALF_HEIGHT_TIME_SCALE_MARK = 0.75;
