export const PATIENT_HEADER_AVATAR_SIZE = 6.375;
export const PATIENT_VIEW_MODAL_AVATAR_SIZE = 13.15;
export const MAX_PETAL_PRACTITIONERS_COUNT = 4;
export const SEPARATED_PETAL_PRACTITIONERS_COUNT = 3;
