export const TODAYS_LOADER_WIDTH = 23;
export const VITALS_LOADER_WIDTH = 8;
export const VITALS_CHART_LOADER_WIDTH = 23;
export const ALLERGIES_LOADER_WIDTH = 8;
export const IMMUNIZATIONS_LOADER_WIDTH = 8;
export const MEDICATION_LOADER_WIDTH = 23;
export const TIMELINE_LOADER_WIDTH = 8;
export const HEALTH_CONDITIONS_LOADER_WIDTH = 23;
export const RESULTS_MENU_LOADER_WIDTH = 8;
export const TEST_RESULTS_LOADER_WIDTH = 23;
export const CHECKOUT_CONTENT_LOADER_WIDTH = 15;
export const TIMESLOT_CONTENT_LOADER_WIDTH = 12;
export const LOCATIONS_CONTENT_LOADER_WIDTH = 11;
export const CHECKOUT_PROVIDER_MODAL_LOADER_WIDTH = 15;

