import { errorTriangular } from '@icons';
import { hideScheduleAppointmentError } from '@redux/actions';

export const ErrorData = {
  UnexpectedSystemError : {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error',
    errorTitle:'Unexpected System Error!',
    errorMessage:'Something went wrong.<br/>Please try again.',
    errorButtonText:'Try Again',
    onAction:hideScheduleAppointmentError,
  },
  GlobalUnexpectedSystemError : {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error',
    errorTitle:'Unexpected System Error!',
    errorMessage:'Something went wrong.<br/>Please try again.',
    errorButtonText:'OK',
    onAction:hideScheduleAppointmentError,
  },
  UnableToFetchData : {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error',
    errorTitle:'Data Load Error!',
    errorMessage:'Unable to fetch few details.',
    errorButtonText:'OK',
    onAction:hideScheduleAppointmentError,
  },
  SkipErrorData: {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error',
    errorTitle:'Couldn\'t perform the action!',
    errorMessage:'Something went wrong.<br/>Please try again.',
    errorButtonText:'OK',
    onAction:hideScheduleAppointmentError,
  },
  sameSlotBooked: {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error',
    errorTitle:'Scheduling Failed!',
    errorMessage:'Oops! Looks like appointment is already taken.<br/>Please try again.',
    errorButtonText:'Try Again',
    onAction:hideScheduleAppointmentError,
  },
  UnableToProcessAppointment : {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error',
    errorTitle:'Scheduling Failed!',
    errorMessage:'Unable to process the appointment request due to system errors.',
    errorButtonText:'Try Again',
    onAction:hideScheduleAppointmentError,
  },
  UnableToFetchDataChooseProvider : {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:false,
    errorHeader:'Error',
    errorTitle:'Couldn\'t get the data!',
    errorMessage:'Unable to fetch the data.<br/>Please try again.',
    errorButtonText:'Try Again',
    onAction:hideScheduleAppointmentError,
  },  
  BadNetwork: {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error',
    errorTitle:'Bad Network!',
    errorMessage:'Please refresh the Page.',
    errorButtonText:'OK',
    onAction:hideScheduleAppointmentError,
  },
  SystemErrorLab : {
    icon:errorTriangular,
    isScheduleAppointmentErrorShown:true,
    errorHeader:'Error', 
    errorTitle:'System Error!',
    errorMessage:'Unable to fetch the details.<br/>Please Try again.',
    errorButtonText:'Try Again',
    onAction:hideScheduleAppointmentError,
  },
};
