CREATE TABLE [dulycv].[ReferralRecommendedProviders] (
    [Identifier]                          VARCHAR (126) NULL,
    [order_id]                            NUMERIC (18)  NOT NULL,
    [referral_id]                         NUMERIC (18)  NULL,
    [referral_status]                     VARCHAR (254) NULL,
    [pat_id]                              VARCHAR (18)  NULL,
    [pat_first_name]                      VARCHAR (200) NULL,
    [pat_last_name]                       VARCHAR (200) NULL,
    [pat_dob]                             DATETIME      NULL,
    [pat_addr_1]                          VARCHAR (50)  NULL,
    [pat_addr_2]                          VARCHAR (50)  NULL,
    [pat_city]                            VARCHAR (50)  NULL,
    [pat_state]                           VARCHAR (254) NULL,
    [pat_zip]                             VARCHAR (60)  NULL,
    [pat_phone]                           VARCHAR (20)  NULL,
    [specialty_id]                        VARCHAR (66)  NULL,
    [specialty_name]                      VARCHAR (254) NULL,
    [referredby_provider_id]              VARCHAR (18)  NULL,
    [referredby_provider_name]            VARCHAR (254) NULL,
    [icd_code]                            VARCHAR (254) NULL,
    [icd_description]                     VARCHAR (200) NULL,
    [referredto_provider_id]              VARCHAR (18)  NULL,
    [referredto_provider_name]            VARCHAR (254) NULL,
    [department_id]                       NUMERIC (18)  NULL,
    [department_name]                     VARCHAR (254) NULL,
    [department_phone]                    VARCHAR (254) NULL,
    [location_id]                         NUMERIC (18)  NULL,
    [location_name]                       VARCHAR (80)  NULL,
    [location_addr_1]                     VARCHAR (254) NULL,
    [location_addr_2]                     VARCHAR (254) NULL,
    [location_city]                       VARCHAR (50)  NULL,
    [location_state]                      VARCHAR (254) NULL,
    [location_zip]                        VARCHAR (60)  NULL,
    [location_distance_from_patient_home] FLOAT (53)    NULL,
    [visit_type_id]                       INT           NOT NULL,
    [visit_type_name]                     VARCHAR (25)  NOT NULL,
    [provider_id]                         VARCHAR (18)  NULL,
    [provider_name]                       VARCHAR (254) NULL,
    [provider_specialty]                  VARCHAR (254) NULL,
    [slot_available_in_next_2_weeks]      VARCHAR (1)   NOT NULL
);

