fieldLayouts:
    c904f488-dfa0-425a-ab8c-cbbe85b84613: { tabs: [{ elements: [{ autocapitalize: true, autocomplete: false, autocorrect: true, class: null, disabled: false, id: null, instructions: null, label: 'Provider Name', max: null, min: null, name: null, orientation: null, placeholder: null, readonly: false, requirable: false, size: null, step: null, tip: null, title: null, type: craft\fieldlayoutelements\EntryTitleField, warning: null, width: 100 }, { fieldUid: b9491aa9-3e00-48b2-a346-82fa33b405fb, instructions: null, label: null, required: true, tip: null, type: craft\fieldlayoutelements\CustomField, warning: null, width: 100 }, { fieldUid: e421dd8c-43bb-448c-84f7-415513374f71, instructions: null, label: null, required: false, tip: null, type: craft\fieldlayoutelements\CustomField, warning: null, width: 100 }], name: 'Insurance Providers', sortOrder: 1 }] }
handle: insuranceProviders
hasTitleField: true
name: 'Insurance Providers'
section: 814af26c-9ee6-423b-baaf-6ec26b5399dc
sortOrder: 1
titleFormat: '{entry.insuranceProviderName|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
