{{- if .Values.azureAADPodIdentity.enabled }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{ .Values.azureAADPodIdentity.aadPodIdName }}
  labels:
    {{- include "webapi.labels" . | nindent 4 }}
spec:
  type: 0
  resourceID: {{ .Values.azureAADPodIdentity.aadPodIdResourceId }}
  clientID: {{ .Values.azureAADPodIdentity.aadPodIdClientId }}
{{- end }}